export default function sitemap() {
  return [
    {
      url: 'https://www.findmygen.com',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: 'https://www.findmygen.com/quiz',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.findmygen.com/compare',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: 'https://www.findmygen.com/blog',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: 'https://www.findmygen.com/blog/gen-z-vs-millennials',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/what-is-gen-alpha',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/gen-x-vs-baby-boomers',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/millennials-vs-gen-x',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/silent-generation-explained',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/gen-z-workplace-guide',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/baby-boomer-retirement',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/gen-alpha-parenting-guide',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/bridging-generation-gaps-at-work',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/blog/cuspers-born-between-generations',
      lastModified: new Date('2025-10-18'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/gen-z',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/millennials',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/gen-x',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/baby-boomers',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/gen-alpha',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/silent-generation',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.findmygen.com/privacy',
      lastModified: new Date('2025-10-17'),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
  ]
}